ignore:
  - "src/ansys/mechanical/core/mechanical_pb2.py"
  - "src/ansys/mechanical/core/mechanical_pb2_grpc.py"

comment:
  layout: "diff"
  behavior: default

coverage:
  status:
    project: false
    patch:
      default:
        # basic
        target: 90%
        if_not_found: success
        if_ci_failed: error
        if_no_uploads: error
